import Link from "next/link";
import { AlertTriangle, CheckCircle2, MessageCircle, XCircle } from "lucide-react";
import { approveTrialRequestAction, rejectTrialRequestAction, saveMenuAction, saveRoleAction, setRegistrationEnabledAction, updateSubscriptionAction } from "@/app/(admin)/admin/actions";
import { AdminTable, dateInput, statusLabel, thaiDate } from "@/components/admin/AdminPrimitives";
import { RolePermissionMatrix, UserPermissionMatrix } from "@/components/admin/PermissionMatrix";
import { StatusBadge } from "@/components/ui/StatusBadge";
import type { AdminViewContentProps } from "@/components/admin/admin-types";

const subscriptionStatuses = ["trialing", "active", "past_due", "readonly", "paused", "cancelled"];
const trialRiskLabels: Record<string, string> = {
  similar_property_name: "ชื่อคล้ายหอในระบบ",
  existing_tenant_phone: "เบอร์ตรงกับผู้เช่าเดิม",
};

export function AdminTrialRequestsView({ trialRequests }: Pick<AdminViewContentProps, "trialRequests">) {
  const pendingCount = trialRequests.filter((item) => item.status === "pending").length;
  return <>
    <section className="admin-trial-summary">
      <div><small>รอตรวจสอบ</small><strong>{pendingCount.toLocaleString("th-TH")}</strong><span>คำขอ</span></div>
      <p>อนุมัติเมื่อยืนยันว่าเป็นผู้ประกอบการจริงแล้วเท่านั้น ระบบจะสร้าง 1 กิจการ 1 หอ และเริ่ม Trial 30 วัน รองรับสูงสุด 100 ห้อง</p>
    </section>
    <section className="admin-trial-list">
      {trialRequests.map((item) => <article className={`admin-trial-request ${item.status}`} key={item.id}>
        <header>
          <div><span className="admin-trial-operator">{item.operator_name}</span><h2>{item.property_name}</h2><small>@{item.username} · ส่งเมื่อ {thaiDate(item.submitted_at)}</small></div>
          <StatusBadge compact label={statusLabel(item.status)} status={item.status} />
        </header>
        <dl>
          <div><dt>อีเมลติดต่อ</dt><dd>{item.contact_email}</dd></div>
          <div><dt>เบอร์โทร</dt><dd>{item.phone}</dd></div>
          <div><dt>จำนวนห้อง</dt><dd>{item.requested_room_count.toLocaleString("th-TH")} ห้อง</dd></div>
          <div><dt>Request ID</dt><dd><code>{item.id}</code></dd></div>
        </dl>
        {item.risk_flags.length ? <div className="admin-trial-risks"><AlertTriangle size={16} /><div><strong>ควรตรวจสอบเพิ่มเติม</strong>{item.risk_flags.map((flag) => <span key={flag}>{trialRiskLabels[flag] ?? flag}</span>)}</div></div> : <div className="admin-trial-clear"><CheckCircle2 size={16} />ไม่พบสัญญาณซ้ำอัตโนมัติ</div>}
        {item.status === "pending" ? <div className="admin-trial-actions">
          <form action={approveTrialRequestAction}><input name="requestId" type="hidden" value={item.id} /><button className="approve" type="submit"><CheckCircle2 size={16} />อนุมัติและเริ่ม Trial</button></form>
          <form action={rejectTrialRequestAction}><input name="requestId" type="hidden" value={item.id} /><input aria-label="เหตุผลที่ปฏิเสธ" maxLength={500} minLength={3} name="reason" placeholder="ระบุเหตุผลที่ปฏิเสธ" required /><button className="reject" type="submit"><XCircle size={16} />ปฏิเสธ</button></form>
        </div> : null}
        {item.rejection_reason ? <p className="admin-trial-rejection"><strong>เหตุผล:</strong> {item.rejection_reason}</p> : null}
      </article>)}
      {!trialRequests.length ? <div className="admin-empty">ยังไม่มีคำขอทดลองใช้</div> : null}
    </section>
  </>;
}

export function AdminLineView() { return <section className="admin-card admin-addon-card"><span><MessageCircle size={28} /></span><div><small>ADD-ON</small><h2>LINE แจ้งเตือน</h2><p>เมนูเตรียมไว้แล้ว แต่ระบบจริงยังไม่ได้เชื่อม LINE Messaging API จึงยังไม่มีการส่งข้อความออก เพื่อไม่ให้หน้า Demo หลอกว่าเปิดใช้บริการแล้ว</p></div><StatusBadge compact label="ยังไม่เชื่อมต่อ" status="inactive" /></section>; }

export function AdminSubscriptionsView({ subscriptions, organizationMap }: Pick<AdminViewContentProps, "subscriptions" | "organizationMap">) { return <section className="admin-card"><AdminTable headers={["กิจการ", "Trial", "สิ้นสุดรอบ", "จัดการสิทธิ์ใช้งาน"]} rows={subscriptions.map((item) => [organizationMap.get(item.organization_id) ?? "—", thaiDate(item.trial_ends_at), thaiDate(item.current_period_end), <form action={updateSubscriptionAction} className="admin-inline-form" key="f"><input name="organizationId" type="hidden" value={item.organization_id} /><select defaultValue={item.status} name="status">{subscriptionStatuses.map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select><input defaultValue={dateInput(item.access_until)} name="accessUntil" type="date" /><button type="submit">บันทึก</button></form>])} /></section>; }

export function AdminRolesView({ roles }: Pick<AdminViewContentProps, "roles">) { return <><section className="admin-card"><div className="admin-card-head"><div><small>ROLE ใหม่</small><h2>เพิ่มบทบาท</h2></div></div><form action={saveRoleAction} className="admin-create-form"><input name="code" pattern="[a-z][a-z0-9_]{2,49}" placeholder="code เช่น auditor" required /><input name="name" placeholder="ชื่อ Role" required /><select name="scopeType" defaultValue="organization"><option value="platform">Platform</option><option value="organization">กิจการ</option><option value="property">หอพัก</option></select><input className="wide" name="description" placeholder="คำอธิบาย" /><button type="submit">เพิ่ม Role</button></form></section><section className="admin-card"><AdminTable headers={["Code", "แก้ไข Role", "ประเภท"]} rows={roles.map((role) => [<code key="c">{role.code}</code>, <form action={saveRoleAction} className="admin-inline-form admin-form-wide" key="f"><input name="roleId" type="hidden" value={role.id} /><input name="name" defaultValue={role.name} required /><select name="scopeType" defaultValue={role.scope_type}><option value="platform">Platform</option><option value="organization">กิจการ</option><option value="property">หอพัก</option></select><input name="description" defaultValue={role.description ?? ""} placeholder="คำอธิบาย" /><select name="status" defaultValue={role.status}><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select><button type="submit">บันทึก</button></form>, role.is_system ? "System" : "กำหนดเอง"])} /></section></>; }

export function AdminPermissionsView({ granularPermissionsReady, params, organizations, roles, matrixActions, matrixMenus, matrixRoles, selectedRoleId, selectedOrganizationId, selectedOrganizationUsers, selectedUserId }: Pick<AdminViewContentProps, "granularPermissionsReady" | "params" | "organizations" | "roles" | "matrixActions" | "matrixMenus" | "matrixRoles" | "selectedRoleId" | "selectedOrganizationId" | "selectedOrganizationUsers" | "selectedUserId">) { return <section className="admin-card admin-permissions-card"><div className="admin-card-head"><div><small>MENU × ACTION</small><h2>กำหนดสิทธิ์การใช้งาน</h2><p>สิทธิ์รายผู้ใช้มีผลเหนือ Role และระบบจะปฏิเสธสิทธิ์ที่ไม่ได้กำหนดไว้โดยอัตโนมัติ</p></div></div>{!granularPermissionsReady ? <div className="admin-notice error">ระบบสิทธิ์แบบละเอียดยังไม่พร้อม กรุณา apply migration <code>20260828101032_granular_menu_permissions.sql</code></div> : <><div className="admin-permission-tabs"><Link className={params.mode !== "user" ? "active" : ""} href="/admin/permissions">สิทธิ์ตาม Role</Link><Link className={params.mode === "user" ? "active" : ""} href="/admin/permissions?mode=user">กำหนดเฉพาะผู้ใช้</Link></div>{params.mode === "user" ? <UserPermissionMatrix actions={matrixActions} menus={matrixMenus} organizations={organizations.map((item) => ({ id: item.id, name: item.name }))} organizationRoles={roles.filter((item) => item.scope_type === "organization" && item.status === "active").map((item) => ({ code: item.code, name: item.name }))} selectedOrganizationId={selectedOrganizationId} users={selectedOrganizationUsers} selectedUserId={selectedUserId} /> : <RolePermissionMatrix actions={matrixActions} menus={matrixMenus} roles={matrixRoles} selectedRoleId={selectedRoleId} />}</>}</section>; }

export function AdminMenusView({ menus, permissions }: Pick<AdminViewContentProps, "menus" | "permissions">) { return <><section className="admin-card"><div className="admin-card-head"><div><small>MENU ใหม่</small><h2>เพิ่มเมนู</h2></div></div><form action={saveMenuAction} className="admin-create-form"><input name="code" pattern="[a-z][a-z0-9_]{2,49}" placeholder="menu_code" required /><input name="label" placeholder="ชื่อเมนู" required /><input name="href" pattern="/.*" placeholder="/path" required /><input name="icon" placeholder="Icon เช่น Circle" /><input name="sortOrder" type="number" defaultValue="100" /><select name="requiredPermission" defaultValue=""><option value="">ไม่กำหนด Permission</option>{permissions.map((permission) => <option key={permission.code} value={permission.code}>{permission.code}</option>)}</select><select name="audience" defaultValue="customer"><option value="admin">Admin</option><option value="customer">Customer</option><option value="all">ทั้งหมด</option></select><button type="submit">เพิ่มเมนู</button></form></section><section className="admin-card"><AdminTable headers={["Code", "แก้ไขเมนู"]} rows={menus.map((item) => [<code key="c">{item.code}</code>, <form action={saveMenuAction} className="admin-inline-form admin-form-wide" key="f"><input name="menuId" type="hidden" value={item.id} /><input name="label" defaultValue={item.label} required /><input name="href" defaultValue={item.href} required /><input name="icon" defaultValue={item.icon} /><input className="admin-number" name="sortOrder" type="number" defaultValue={item.sort_order} /><select name="requiredPermission" defaultValue={item.required_permission ?? ""}><option value="">ไม่กำหนด</option>{permissions.map((permission) => <option key={permission.code} value={permission.code}>{permission.code}</option>)}</select><select name="audience" defaultValue={item.audience}><option value="admin">Admin</option><option value="customer">Customer</option><option value="all">ทั้งหมด</option></select><select name="status" defaultValue={item.status}><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select><button type="submit">บันทึก</button></form>])} /></section></>; }

export function AdminAuditView({ audits, profileMap }: Pick<AdminViewContentProps, "audits" | "profileMap">) { return <section className="admin-card"><AdminTable headers={["เวลา", "ผู้ดำเนินการ", "เหตุการณ์", "ข้อมูล", "รายละเอียด"]} rows={audits.map((item) => [thaiDate(item.created_at), profileMap.get(item.actor_user_id ?? "") ?? "ระบบ", item.action, `${item.entity_type}${item.entity_id ? ` · ${item.entity_id}` : ""}`, <details key="d"><summary>ดูการเปลี่ยนแปลง</summary><pre>{JSON.stringify({ before: item.before_data, after: item.after_data }, null, 2)}</pre></details>])} empty="ยังไม่มี Audit Log" /></section>; }

export function AdminSettingsView({ registration }: Pick<AdminViewContentProps, "registration">) { return <section className="admin-card registration-control"><div><small>การตั้งค่าระบบ</small><h2>เปิด/ปิดคำขอทดลองใช้</h2><p>ควบคุม API ที่รับคำขอจาก <code>longtua.com/apartment/register</code> ผู้ใช้เดิมยังเข้าสู่ระบบได้ตามปกติ และคำขอที่ส่งแล้วไม่ถูกลบ</p></div><div className="registration-state"><span className={registration.enabled ? "on" : "off"}>{registration.enabled ? "เปิดรับคำขอ" : "ปิดรับคำขอ"}</span><form action={setRegistrationEnabledAction}><input type="hidden" name="enabled" value={registration.enabled ? "false" : "true"} /><button className={registration.enabled ? "danger" : "primary"} type="submit">{registration.enabled ? "ปิดรับคำขอ" : "เปิดรับคำขอ"}</button></form></div></section>; }
