import { Hotel, KeyRound, ReceiptText, WalletCards } from "lucide-react";
import { AdminTable, money, thaiDate } from "@/components/admin/AdminPrimitives";
import { StatusBadge } from "@/components/ui/StatusBadge";
import type { AdminViewContentProps } from "@/components/admin/admin-types";

export function AdminMetersView({ meters, organizationMap, propertyMap, roomMap, latestReadingByMeter, metersReady }: Pick<AdminViewContentProps, "meters" | "organizationMap" | "propertyMap" | "roomMap" | "latestReadingByMeter" | "metersReady">) {
  return <section className="admin-card"><AdminTable headers={["กิจการ", "หอ/ห้อง", "ประเภท", "เลขล่าสุด", "หน่วยใช้", "วันที่จด", "สถานะ"]} rows={meters.map((item) => { const reading = latestReadingByMeter.get(item.id); return [organizationMap.get(item.organization_id) ?? "—", `${propertyMap.get(item.property_id) ?? "—"} / ${roomMap.get(item.room_id) ?? "—"}`, item.meter_type === "electric" ? "ไฟฟ้า" : "น้ำ", reading ? Number(reading.current_value).toLocaleString("th-TH") : "—", reading ? Number(reading.usage_value).toLocaleString("th-TH") : "—", thaiDate(reading?.read_at ?? null), <StatusBadge compact key="s" status={item.status} />]; })} empty={!metersReady ? "ตารางมิเตอร์ยังไม่พร้อม" : "ยังไม่มีมิเตอร์"} /></section>;
}

export function AdminInvoicesView({ invoices, organizationMap, propertyMap, roomMap, invoicesReady }: Pick<AdminViewContentProps, "invoices" | "organizationMap" | "propertyMap" | "roomMap" | "invoicesReady">) {
  return <section className="admin-card"><AdminTable headers={["กิจการ", "เลขที่ใบแจ้งหนี้", "หอ/ห้อง", "วันที่ออก", "ครบกำหนด", "ยอดรวม", "คงเหลือ", "สถานะ"]} rows={invoices.map((item) => [organizationMap.get(item.organization_id) ?? "—", item.invoice_number, `${propertyMap.get(item.property_id) ?? "—"} / ${roomMap.get(item.room_id) ?? "—"}`, thaiDate(item.issued_at), thaiDate(item.due_at), money(Number(item.total)), money(Number(item.balance_due)), <StatusBadge compact key="s" status={item.status} />])} empty={!invoicesReady ? "ตารางใบแจ้งหนี้ยังไม่พร้อม" : "ยังไม่มีใบแจ้งหนี้"} /></section>;
}

export function AdminPaymentsView({ payments, organizationMap, propertyMap, paymentsReady }: Pick<AdminViewContentProps, "payments" | "organizationMap" | "propertyMap" | "paymentsReady">) {
  return <section className="admin-card"><AdminTable headers={["กิจการ", "เลขที่ใบเสร็จ", "หอพัก", "วันที่รับ", "ยอดเงิน", "ช่องทาง", "อ้างอิง", "สถานะ"]} rows={payments.map((item) => [organizationMap.get(item.organization_id) ?? "—", item.receipt_number, propertyMap.get(item.property_id) ?? "—", thaiDate(item.paid_at), money(Number(item.amount)), item.method, item.reference || "—", <StatusBadge compact key="s" status={item.status} />])} empty={!paymentsReady ? "ตารางรับชำระยังไม่พร้อม" : "ยังไม่มีรายการรับชำระ"} /></section>;
}

export function AdminReceivablesView({ invoices, organizationMap, roomMap }: Pick<AdminViewContentProps, "invoices" | "organizationMap" | "roomMap">) {
  return <section className="admin-card"><AdminTable headers={["กิจการ", "เลขที่ใบแจ้งหนี้", "ห้อง", "ครบกำหนด", "ยอดรวม", "ยอดค้าง", "สถานะ"]} rows={invoices.filter((item) => Number(item.balance_due) > 0 && item.status !== "void").map((item) => [organizationMap.get(item.organization_id) ?? "—", item.invoice_number, roomMap.get(item.room_id) ?? "—", thaiDate(item.due_at), money(Number(item.total)), <strong key="b">{money(Number(item.balance_due))}</strong>, <StatusBadge compact key="s" status={item.status} />])} empty="ไม่มียอดค้างชำระ" /></section>;
}

export function AdminReportsView({ properties, rooms, organizations, invoices, payments, totalCollected, totalOutstanding, totalBilled, occupiedRooms }: Pick<AdminViewContentProps, "properties" | "rooms" | "organizations" | "invoices" | "payments" | "totalCollected" | "totalOutstanding" | "totalBilled" | "occupiedRooms">) {
  return <><section className="admin-stats"><article><span><Hotel size={20} /></span><div><small>หอพักทั้งหมด</small><strong>{properties.length}</strong></div></article><article><span><KeyRound size={20} /></span><div><small>อัตราเข้าพัก</small><strong>{rooms.length ? Math.round(occupiedRooms / rooms.length * 100) : 0}%</strong></div></article><article><span><WalletCards size={20} /></span><div><small>รับชำระสะสม</small><strong>{money(totalCollected)}</strong></div></article><article><span><ReceiptText size={20} /></span><div><small>ยอดค้างทั้งหมด</small><strong>{money(totalOutstanding)}</strong></div></article></section><section className="admin-card"><div className="admin-card-head"><div><small>PLATFORM FINANCE</small><h2>สรุปรายกิจการ</h2></div><strong>ยอดออกบิล {money(totalBilled)}</strong></div><AdminTable headers={["กิจการ", "หอพัก", "ห้อง", "ออกบิล", "รับชำระ", "ยอดค้าง"]} rows={organizations.map((organization) => { const orgInvoices = invoices.filter((item) => item.organization_id === organization.id), orgPayments = payments.filter((item) => item.organization_id === organization.id && item.status === "confirmed"); return [organization.name, properties.filter((item) => item.organization_id === organization.id).length, rooms.filter((item) => item.organization_id === organization.id).length, money(orgInvoices.reduce((sum, item) => sum + Number(item.total), 0)), money(orgPayments.reduce((sum, item) => sum + Number(item.amount), 0)), money(orgInvoices.reduce((sum, item) => sum + Number(item.balance_due), 0))]; })} /></section></>;
}
