"use client";

import { useMemo, useState } from "react";
import { Banknote, CalendarCheck, Clock3, CreditCard, ExternalLink } from "lucide-react";
import { recordPaymentAction, reviewPaymentSubmissionAction } from "@/app/(portal)/resource-actions";
import { CollectionToolbar } from "@/components/portal/CollectionToolbar";
import { EmptyState, Field, Modal, PageHeader, PortalForm, SelectField, StatusBadge } from "@/components/portal/PortalUI";
import { money, thaiDate } from "@/lib/format";
import type { Invoice, Payment, Property, Tenant } from "@/components/portal/types";
import { validatePayment } from "@/lib/portal/validation.mjs";

type PaymentSubmission = { id: string; tenant_id: string; invoice_id: string; amount: number; paid_at: string; method: string; reference: string | null; slip_path: string; note: string | null; status: string; created_at: string; slipUrl: string | null };

export function PaymentsPage({ organizationId, payments, invoices, properties, tenants, submissions, canCreate }: { organizationId: string; payments: Payment[]; invoices: Invoice[]; properties: Property[]; tenants: Tenant[]; submissions: PaymentSubmission[]; canCreate: boolean }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [method, setMethod] = useState("all");
  const propertyMap = useMemo(() => new Map(properties.map((item) => [item.id, item.name])), [properties]);
  const tenantMap = useMemo(() => new Map(tenants.map((item) => [item.id, item.full_name])), [tenants]);
  const invoiceMap = useMemo(() => new Map(invoices.map((item) => [item.id, item.invoice_number])), [invoices]);
  const openInvoices = invoices.filter((item) => Number(item.balance_due) > 0 && item.status !== "void");
  const month = new Date().toISOString().slice(0, 7).replace("-", "");
  const filtered = useMemo(() => { const keyword = query.trim().toLocaleLowerCase("th"); return payments.filter((item) => (method === "all" || item.method === method) && (!keyword || [item.receipt_number, propertyMap.get(item.property_id), item.reference].some((value) => value?.toLocaleLowerCase("th").includes(keyword)))); }, [method, payments, propertyMap, query]);
  return <>
    <PageHeader title="รับชำระ" description="บันทึกยอดรับเงินจริงและตัดยอดคงเหลือของใบแจ้งหนี้" actionLabel={canCreate ? "รับชำระเงิน" : undefined} onAction={() => setOpen(true)} />
    <section className="portal-summary-strip"><div><strong>{money(payments.filter((item) => item.status === "confirmed").reduce((sum, item) => sum + Number(item.amount), 0))}</strong><span>รับชำระยืนยันแล้ว</span></div><div><strong>{payments.length.toLocaleString("th-TH")}</strong><span>รายการทั้งหมด</span></div><div><strong>{openInvoices.length.toLocaleString("th-TH")}</strong><span>ใบแจ้งหนี้รอชำระ</span></div></section>
    {submissions.length ? <section className="portal-payment-review"><header><div><h2>หลักฐานรอตรวจสอบ</h2><p>ตรวจยอดและชื่อบัญชีก่อนกดยืนยัน ระบบจะตัดยอดใบแจ้งหนี้ทันที</p></div><span>{submissions.length.toLocaleString("th-TH")} รายการ</span></header><div>{submissions.map((item) => <article key={item.id}><div className="portal-review-main"><span><Clock3 size={19} /></span><div><strong>{tenantMap.get(item.tenant_id) ?? "ผู้เช่า"}</strong><small>{invoiceMap.get(item.invoice_id) ?? "ใบแจ้งหนี้"} · โอนเมื่อ {thaiDate(item.paid_at)}</small></div><b>{money(Number(item.amount))}</b></div><dl><div><dt>ช่องทาง</dt><dd>{item.method}</dd></div><div><dt>อ้างอิง</dt><dd>{item.reference || "—"}</dd></div></dl>{item.note ? <p>{item.note}</p> : null}<footer>{item.slipUrl ? <a href={item.slipUrl} rel="noreferrer" target="_blank"><ExternalLink size={15} /> เปิดหลักฐาน</a> : <span>ไม่สามารถเปิดไฟล์ได้</span>}<form action={async (formData) => { await reviewPaymentSubmissionAction(formData); }}><input name="organizationId" type="hidden" value={organizationId} /><input name="submissionId" type="hidden" value={item.id} /><input name="decision" type="hidden" value="reject" /><input aria-label="เหตุผลที่ไม่อนุมัติ" name="rejectionReason" placeholder="เหตุผลที่ส่งกลับ" required /><button className="portal-secondary" type="submit">ส่งกลับ</button></form><form action={async (formData) => { await reviewPaymentSubmissionAction(formData); }}><input name="organizationId" type="hidden" value={organizationId} /><input name="submissionId" type="hidden" value={item.id} /><input name="decision" type="hidden" value="approve" /><button className="portal-primary" type="submit">ยืนยันยอด</button></form></footer></article>)}</div></section> : null}
    <CollectionToolbar title="ประวัติรับชำระ" description={`พบ ${filtered.length.toLocaleString("th-TH")} รายการ`} query={query} onQueryChange={setQuery} placeholder="ค้นหาเลขที่ใบเสร็จ หอพัก หรือเลขอ้างอิง" filter={{ label: "กรองช่องทางชำระ", value: method, onChange: setMethod, options: [{ value: "all", label: "ทุกช่องทาง" }, { value: "cash", label: "เงินสด" }, { value: "transfer", label: "โอนธนาคาร" }, { value: "promptpay", label: "PromptPay" }, { value: "card", label: "บัตร" }, { value: "other", label: "อื่น ๆ" }] }} />
    {filtered.length ? <section className="portal-collection-grid">{filtered.map((item) => <article className="portal-record-card payment-card" key={item.id}><header><span className="portal-record-icon success"><Banknote aria-hidden="true" size={20} /></span><div><h2>{item.receipt_number}</h2><small>{propertyMap.get(item.property_id) ?? "ไม่พบหอพัก"}</small></div><StatusBadge status={item.status} /></header><div className="portal-payment-amount"><small>ยอดรับชำระ</small><strong>{money(Number(item.amount))}</strong></div><dl className="portal-record-metrics"><div><dt>ช่องทาง</dt><dd><CreditCard aria-hidden="true" size={14} /> {item.method}</dd></div><div><dt>เลขอ้างอิง</dt><dd>{item.reference || "—"}</dd></div></dl><footer><span><CalendarCheck aria-hidden="true" size={14} /> รับเมื่อ {thaiDate(item.paid_at)}</span></footer></article>)}</section> : <EmptyState title={payments.length ? "ไม่พบรายการรับชำระ" : "ยังไม่มีรายการรับชำระ"} description={payments.length ? "ลองเปลี่ยนคำค้นหาหรือช่องทางชำระ" : "เมื่อรับชำระจากใบแจ้งหนี้ รายการจะปรากฏที่นี่"} />}
    {open ? <Modal title="รับชำระเงิน" description="เลือกใบแจ้งหนี้และระบุยอดที่รับจริง ระบบรองรับการชำระบางส่วน" onClose={() => setOpen(false)}>
      <PortalForm action={recordPaymentAction} organizationId={organizationId} validate={validatePayment} onSuccess={() => setOpen(false)} submitLabel="ยืนยันรับชำระ">
        {(errors, clear) => <><SelectField label="ใบแจ้งหนี้" name="invoiceId" required error={errors.invoiceId} clear={clear} options={openInvoices.map((item) => ({ value: item.id, label: `${item.invoice_number} · คงเหลือ ${money(Number(item.balance_due))}` }))} onChange={(value, form) => { const invoice = openInvoices.find((item) => item.id === value); if (invoice && form) (form.elements.namedItem("amount") as HTMLInputElement).value = String(invoice.balance_due); }} /><div className="portal-form-grid"><Field label="เลขที่ใบเสร็จ" name="receiptNumber" required defaultValue={`REC-${month}-${String(payments.length + 1).padStart(4, "0")}`} error={errors.receiptNumber} clear={clear} /><Field label="ยอดรับชำระ" name="amount" required type="number" min="0.01" step="0.01" error={errors.amount} clear={clear} /></div><SelectField label="ช่องทาง" name="method" required defaultValue="transfer" error={errors.method} clear={clear} options={[{ value: "cash", label: "เงินสด" }, { value: "transfer", label: "โอนธนาคาร" }, { value: "promptpay", label: "PromptPay" }, { value: "card", label: "บัตร" }, { value: "other", label: "อื่น ๆ" }]} /><Field label="เลขอ้างอิง" name="reference" error={errors.reference} clear={clear} /></>}
      </PortalForm>
    </Modal> : null}
  </>;
}
