export type Organization = { id: string; name: string; status: string; owner_user_id: string; created_at: string };
export type Profile = { id: string; username: string; display_name: string; phone: string | null; status: string; created_at: string };
export type Membership = { organization_id: string; user_id: string; role_code: string; status: string };
export type Subscription = { organization_id: string; status: string; trial_ends_at: string | null; current_period_end: string | null; access_until: string | null; max_properties?: number | null; max_rooms?: number | null; max_slip_verifications?: number | null; plan_code?: string | null };
export type SubscriptionPlan = {
  code: string;
  name: string;
  badge: string | null;
  popular: boolean;
  price_monthly: number;
  period: string;
  target_audience: string;
  max_properties: number;
  max_properties_label: string;
  max_rooms: number;
  max_rooms_label: string;
  max_users: number;
  max_users_label: string;
  max_slip_verifications: number;
  max_slip_verifications_label: string;
  features: string[];
  cta_label: string;
  cta_href: string;
  cta_variant: string;
  sort_order: number;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
};
export type Property = { id: string; organization_id: string; name: string; address: string | null; phone: string | null; status: string; created_at: string };
export type Room = { id: string; organization_id: string; property_id: string; room_number: string; floor: string | null; base_rent: number; status: string };
export type Tenant = { id: string; organization_id: string; full_name: string; phone: string | null; email: string | null; status: string; created_at: string };
export type Lease = { id: string; organization_id: string; property_id: string; room_id: string; primary_tenant_id: string; lease_number: string; start_date: string; end_date: string | null; rent_amount: number; status: string };
export type Meter = { id: string; organization_id: string; property_id: string; room_id: string; meter_type: string; serial_number: string | null; status: string };
export type MeterReading = { meter_id: string; current_value: number; usage_value: number; read_at: string };
export type Invoice = { id: string; organization_id: string; property_id: string; room_id: string; invoice_number: string; issued_at: string; due_at: string; total: number; balance_due: number; status: string };
export type Payment = { id: string; organization_id: string; property_id: string; receipt_number: string; paid_at: string; amount: number; method: string; reference: string | null; status: string };
export type Role = { id: string; code: string; name: string; scope_type: string; description: string | null; is_system: boolean; status: string };
export type Permission = { code: string; module: string; action: string; name: string; description: string | null; status: string };
export type Menu = { id: string; code: string; label: string; href: string; icon: string; sort_order: number; required_permission: string | null; audience: string; status: string };
export type Audit = { id: string; actor_user_id: string | null; action: string; entity_type: string; entity_id: string | null; before_data: unknown; after_data: unknown; created_at: string };
export type TrialRequest = { id: string; auth_user_id: string; username: string; operator_name: string; property_name: string; contact_email: string; phone: string; requested_room_count: number; status: string; risk_flags: string[]; submitted_at: string; reviewed_at: string | null; rejection_reason: string | null };
export type MatrixAction = { code: string; name: string };
export type MatrixMenu = { id: string; code: string; label: string; actionCodes: string[] };
export type MatrixRole = { id: string; code: string; name: string; values: Record<string, boolean> };
export type SelectedUser = { id: string; username: string; name: string; roleCode: string; roleName: string; values: Record<string, "inherit" | "allow" | "deny"> };

export type AdminViewContentProps = {
  view: string;
  title: string;
  description: string;
  params: { mode?: "role" | "user"; role?: string; organization?: string; user?: string; saved?: string; error?: string };
  catalogReady: boolean;
  granularPermissionsReady: boolean;
  organizationCount: number;
  profileCount: number;
  organizations: Organization[];
  profiles: Profile[];
  memberships: Membership[];
  subscriptions: Subscription[];
  subscriptionPlans: SubscriptionPlan[];
  properties: Property[];
  rooms: Room[];
  tenants: Tenant[];
  leases: Lease[];
  meters: Meter[];
  invoices: Invoice[];
  payments: Payment[];
  roles: Role[];
  permissions: Permission[];
  menus: Menu[];
  audits: Audit[];
  trialRequests: TrialRequest[];
  propertiesReady: boolean;
  roomsReady: boolean;
  tenantsReady: boolean;
  leasesReady: boolean;
  metersReady: boolean;
  invoicesReady: boolean;
  paymentsReady: boolean;
  registration: { enabled: boolean };
  systemAdminIds: Set<string>;
  organizationMap: Map<string, string>;
  profileMap: Map<string, string>;
  propertyMap: Map<string, string>;
  roomMap: Map<string, string>;
  tenantMap: Map<string, string>;
  latestReadingByMeter: Map<string, MeterReading>;
  memberCountByOrganization: Map<string, number>;
  organizationCountByUser: Map<string, number>;
  matrixActions: MatrixAction[];
  matrixMenus: MatrixMenu[];
  matrixRoles: MatrixRole[];
  selectedRoleId: string;
  selectedOrganizationId: string;
  selectedOrganizationUsers: SelectedUser[];
  selectedUserId: string;
  totalBilled: number;
  totalOutstanding: number;
  totalCollected: number;
  occupiedRooms: number;
};
