import { Clock3, FileCheck2, ReceiptText } from "lucide-react";
import { TenantPaymentForm } from "@/components/tenant/TenantPaymentForm";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { money, thaiDate } from "@/lib/format";
import { loadTenantPortalData } from "@/lib/tenant/data";

export default async function TenantBillsPage() {
  const data = await loadTenantPortalData();
  const payable = data.invoices.filter((item) => Number(item.balance_due) > 0 && !["paid", "void"].includes(item.status));
  return <><header className="tenant-page-heading"><div><span>การเงินของฉัน</span><h1>บิลและชำระเงิน</h1><p>ดูรายละเอียดค่าใช้จ่ายและส่งหลักฐานให้เจ้าของตรวจสอบ</p></div><span className="tenant-home-icon"><ReceiptText size={22} /></span></header>{payable.map((invoice) => { const items = data.invoiceItems.filter((item) => item.rent_invoice_id === invoice.id); const pending = data.submissions.find((item) => item.invoice_id === invoice.id && item.status === "pending"); const setting = data.settings.find((item) => item.property_id === invoice.property_id); return <article className="tenant-bill-card" key={invoice.id}><header><div><h2>{invoice.invoice_number}</h2><p>ออกเมื่อ {thaiDate(invoice.issued_at)} · ครบกำหนด {thaiDate(invoice.due_at)}</p></div><StatusBadge status={invoice.status} /></header><div className="tenant-bill-lines">{items.map((item) => <div key={item.id}><span><strong>{item.item_type === "rent" ? "ค่าเช่า" : item.item_type === "electric" ? "ค่าไฟ" : item.item_type === "water" ? "ค่าน้ำ" : item.description}</strong><small>{item.description}</small></span><b>{money(Number(item.amount))}</b></div>)}</div><footer><span>ยอดคงเหลือ</span><strong>{money(Number(invoice.balance_due))}</strong></footer>{setting?.promptpay_id ? <div className="tenant-payment-destination"><span>PromptPay / บัญชีรับเงิน</span><strong>{setting.promptpay_id}</strong><small>{setting.account_name || "กรุณาตรวจสอบชื่อบัญชีก่อนโอน"}</small></div> : null}{pending ? <div className="tenant-pending"><Clock3 size={18} /><div><strong>ส่งหลักฐานแล้ว</strong><span>รอเจ้าของตรวจสอบยอด {money(Number(pending.amount))}</span></div></div> : <TenantPaymentForm invoice={{ id: invoice.id, invoice_number: invoice.invoice_number, balance_due: Number(invoice.balance_due) }} userId={data.context.userId} />}</article>; })}{!payable.length ? <section className="tenant-clear-state"><FileCheck2 size={24} /><strong>ไม่มีบิลที่ต้องชำระ</strong><span>รายการที่ชำระแล้วจะยังอยู่ในประวัติด้านล่าง</span></section> : null}<section className="tenant-section"><header><div><h2>ประวัติแจ้งชำระ</h2><p>สถานะหลักฐานที่คุณส่ง</p></div></header><div className="tenant-submission-list">{data.submissions.map((item) => <article key={item.id}><div><strong>{money(Number(item.amount))}</strong><span>{thaiDate(item.paid_at)} · {item.method}</span></div><StatusBadge status={item.status} />{item.status === "rejected" && item.rejection_reason ? <p>{item.rejection_reason}</p> : null}</article>)}</div></section></>;
}
